### ISSUE TITLE
Create component gallery

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#10]
Issue created but @brauliodiez needs to work on definition

We need to create a component gallery:

<img width="225" alt="image" src="https://github.com/Lemoncode/quickmock/assets/1457912/357c778f-1b8c-48e0-989d-302dea611049">

Just only the list (not the _components header_)

The idea could be just to create a flexbox container (wrap) and include this components there.

This gallery will be resued in the containers and shapes section, so we can create first a generic list container.

Proposal:

- Under `common/components` let's create a `shape-gallery` folder.

And let's define a generic model

_./src/common/components/gallery/model.ts_

```ts
interface ItemInfo {
   thumbnailSrc : string; // svg link
   type : string; // this will be passed along when needed
}
```

Then we will implement a `ItemComponent`

_./src/common/components/gallery/item-component.ts_

```tsx
interface Props {
    const itemInfo: ItemInfo;
}
export const ItemComponent  : React.FC<Props> = (props) => {
   // TODO add a flexbox container
   // display the picture
}
```

The create a `GalleryComponent`

```tsx
interface Props {
   const itemCollection : ItemInfo[];
}

const GalleryComponent : React.FC<Props> = (props) => {
  const {itemCollection} = props;

  return (
     <div> // TODO flex container wrap here
       // TODO: add a map here
       // Per item just instantiate the ItemInfo component
     </div>
  );
}
```

About sample SVGs you can find them (there are three created):

https://github.com/brauliodiez/konba-playground/tree/main/public/widgets

**Comment by jsanzdev** [comment]
Creo que lo he hecho.

<img width="731" alt="image" src="https://github.com/Lemoncode/quickmock/assets/16939238/d4d1002e-52fe-4401-8f98-107a969132cc">

El proyecto de momento no tiene la sidebar, sale arriba.
