### ISSUE TITLE
Delete Key not working 

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#367]
Cannot delete a shape using the keyboard, check if this happens on Mac, Windows, Linux

**Comment by oleojake** [comment]
It's a shortcut thing, you delete it with (Ctrl + ↩ ) I think it's more logical to use only the key ↩ and also add the Delete key

**Comment by brauliodiez** [comment]
Great, I would go for that solution

I will assign to you since you have it under control, thanks
