### ISSUE TITLE
Create a link component

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#431]
We need to add a new components under "Components" category:

- A link component.
- Is a text (by default blue color) and underlined.
- The user can do inline editing (double click on the link change the text).
- The user can change the color of the text (props)
- Add a check box to show hide the underlined text

Created the component under: src/common/components/mock-components/front-text-components

Difined props components: pods/canvas/model/shape-other-props.utlis.ts

Defined ShapeType. core/model/index.ts

Same file ShapeDisplayName

Defined render component pods/canvas/shape-render/simple-text-components

defined option on pods/canvas/shape-render/index.tsx

Septs:

1- create simple shape component
2- create render component
3- create other props

**Comment by josemitoribio** [comment]
Hola @brauliodiez , me gustaría trabajar en este issue. Cuando puedas me das los permisos. ¡Gracias!
