### ISSUE TITLE
Center text inside a shape

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#61]
We need a consistent way to center a text inside a box.

e.g. 

The button has a text inside and needs to be centered.

You have to check how to do this using konba, and you can take the button shape as lab to test it, once you get it working maybe we can promote this something reusable

**Comment by oleojake** [comment]
@brauliodiez it seems easy using the property align="center" on the Text Component.

![Image](https://github.com/user-attachments/assets/f5df6188-40e6-4d40-9174-a9b2b4bf008d)
