### ISSUE TITLE
Add three ellipsis if text does not fit

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#62]
Sometimes a long text may not if in the space of the shape, right now we are giving a fix width and the text is just clipped, but it's does not clipped if for instance is a long word.

It would be nice to implement something like HTML does, just show the text with some ellipsis (...) at the end if it doesn't fit

**Comment by oleojake** [comment]
@brauliodiez we can do this by adding these properties in the konva text component

- ellipsis={true}
- wrap='none'



![Image](https://github.com/user-attachments/assets/44831971-bb20-43d2-a239-764447519c79)
