### ISSUE TITLE
Add Unit tests to zIndexutils

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#65]
zindex.util.ts

Methods

moveZIndexToTop
moveZIndexToBottom
moveZIndexDownOneLevel
moveZIndexTopOneLevel

Ask @antonio06 for more info

**Comment by oleojake** [comment]
@antonio06 I think I could handle this task as I have created the functions before. Beside checking the correct performance of each function, I thought in some corner cases like: 
- The shape id is not found
- The list of shapes is empty
- The element is already in the target position.

I have doubts about where I should place the .spec.ts file in the project architecture. Should I create a folder inside /src/ or similar?
